### ISSUE TITLE
map insertion routine

### ISSUE THREAD

**Issue by MostafaAmr45** [sbme-tutorials/sbme-tutorials.github.io#16]
I think there is a tiny fault in slide 67 in week 7. I didn't find the uniqueness check inside the insertion routine as it supposed to be. please check this slide again and if I'm right kindly correct it, and if I'm wrong my apologies in advance. :hatching_chick:

**Comment by A-Alaa** [comment]
I don't find anything relevant to insertion in map in the slide 67 or in the entire slides. The insertion is demonstrated one time for **BST** and another time for **Set**. So if you mean set insertion (`add` function), we guarantee uniqueness just with the following cases:

```c++
void add( BSTNode *&tree, int data )
{
    if ( isEmpty( tree ))
        tree = new BSTNode{ data , nullptr , nullptr };
    else
    {
        if ( data < tree->data )
            add( tree->left, data );
        else if( data > tree->data )
            add( tree->right, data );
    }
}
```

Insertion will only take place when `data < tree->data` or `data > tree->data`. But something might be confusing in the slides, that we shouldn't mention that we **check** for uniqueness, because the routine itself **guarantees** no duplicates.

**Comment by MostafaAmr45** [comment]
I didn't notice that the routine itself guarantees no duplicates. but
you're right, maybe a small comment after the if condition to clarify the
uniqueness check would be fine.
And thanks again for the prompt reply.

**Comment by A-Alaa** [comment]
Added comment now
